[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "discussion-agents"
authors = [
    {name = "Vincent Tu", email = "tuvincent0106@gmail.com"}
]
description = "Multi-agent discussions."
version = "1.0.0"
requires-python = ">=3.11"
keywords = ["multi-agent", "LLM"]
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    # core dependencies
    "cookiecutter",
    "openai",
    "tiktoken",
    "torch",
    "numpy",
    "langchain",
    "langchain-experimental",
    "faiss-cpu", # For CPU Installation
    "chromadb",
    "langroid",
    "camel @ git+https://github.com/camel-ai/camel.git@v0.1.0",

    # youtube dependencies
    "youtube-dl",
    "pytube",
    "pydub",
    "librosa",
    "pafy",
    "yt_dlp",

    # pip install --upgrade --force-reinstall "git+https://github.com/ytdl-org/youtube-dl.git"
    "youtube-transcript-api",
    "opencv-python",

    # backwards compatibility
    "pathlib2"
]
dynamic = ["readme"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "black",
    "pydocstyle",
    "toml",
    "ipython",
    "Sphinx",
    "flake8",
    "python-dotenv>=0.5.1",
    
    # "twine",
    # "build"
]

[project.urls]
Repository = "https://github.com/alckasoc/discussion-agents"