name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "discussion-agents/**"
      - "tests/**"
      - ".github/workflows/ci.yml"
  push:
    branches:
      - main
    paths:
      - "discussion-agents/**"
      - "tests/**"
      - ".github/workflows/ci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./discussion-agents/
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt

    - name: Install Poetry
      run: |
        pip install poetry
        poetry --version

    - name: Install Dependencies
      run: |
        poetry install

    - name: Run Black auto-formatting
      run: |
        poetry run black --check src ../tests